version: '3.8'

services:

  # Nginx
  nginx:
    image: nginx:latest #wybrany obraz
    ports: #deklaracja portow
      - 6660:80 
    volumes: #podpiecie wolumenow
      - ./src:/var/www/php #wolumen z plikiem index.php
      - ./nginx/conf.d:/etc/nginx/conf.d #wolumen z plikiem .conf
    depends_on: #zaleznosci - czekaj na uruchomienie uslugi php
      - php
    networks: #sieci - frontend i backend
      - frontend
      - backend

  # PHP
  php:
    image: php:8.1-fpm #wybrany obraz
    working_dir: /var/www/php #katalog roboczy
    volumes: #podpiecie wolumenow
      - ./src:/var/www/php #wolumen z plikiem index.php
    depends_on: #zaleznosci - czekaj na usluge mysql
      - mysql
    networks: #sieci - tylko backend
      - backend

  # MySQL
  mysql:
    image: mysql:latest #wybrany obraz
    environment: #zmienne srodowiskowe
      MYSQL_ROOT_PASSWORD: root #haslo root'a
      MYSQL_ROOT_HOST: "%"
    volumes: #wolumen - aby baza nie byla kasowana po wylaczeniu kontenera
      - mysqldata:/var/lib/mysql
    networks: #sieci - tylko backend
      - backend
  
  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin #wybrany obraz
    ports: #deklaracja portow
      - 6001:80
    environment: #zmienne srodowiskowe
      PMA_HOST: mysql #nazwa serwera - usluga mysql
    depends_on: #zaleznosci - czekaj na mysql
      - mysql
    networks: #sieci - tylko backend
      - backend
        
# Wolumeny
volumes:
  mysqldata:
# Sieci
networks:
  frontend:
  backend:
