version: '3.8'

# Services
services:

  # Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - 6660:80
    volumes:
      - ./src:/var/www/php
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - frontend
      - backend


  # PHP Service
  php:
    image: php:8.1-fpm
    working_dir: /var/www/php
    volumes:
      - ./src:/var/www/php
    depends_on:
      - mysql
    networks:
      - backend

  # MySQL Service
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - backend
  
  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 6001:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - backend
        

# Volumes
volumes:
  mysqldata:
networks:
  frontend:
  backend: